#!/usr/bin/env bash

cd /opt/blog

with_parameter=false

if [ -n $1 ] && [ $1 == "-a" ]
then
    with_parameter=true
    shift
fi

if [[ ! -n $1 ]] 
then
	echo "must provide article name"
	exit 1
fi

# new hexo page
hexo new $1

cd "/opt/blog/source/_posts"

vim "$1.md"

sleep 1
echo "Write successfully"

# upload new to github
hexo g

if [ ${witt_parameter} == true ]
then
	# run expect script
	/opt/blog/sh/upload
fi
